routes/admin.php
<?php

Route::group(['prefix' => 'admin'], function() {
    //登录展示页面
    Route::get('/login', '\App\Admin\Controllers\LoginController@index');
    //登录行为
     Route::post('/login', '\App\Admin\Controllers\LoginController@login');
    //退出行为
     Route::get('/logout', '\App\Admin\Controllers\LoginController@logout');

    //后台首页
    Route::get('/home', '\App\Admin\Controllers\HomeController@index');
    //管理人员
    Route::get('/users', '\App\Admin\Controllers\UserController@index');
    Route::get('/users/create', '\App\Admin\Controllers\UserController@create');
    Route::post('/users/store', '\App\Admin\Controllers\UserController@store');
    //文章审核页面
    Route::get('/posts', '\App\Admin\Controllers\PostController@index');
    //文章审核行为
    Route::post('/posts', '\App\Admin\Controllers\PostController@status');

    //专题
    Route::resource('topics', '\App\Admin\Controllers\TopicController',
    ['only' => ['index','create','store','destroy']]);
    

    Route::group(['middleware' => 'auth:admin'], function() {
        //首页

    });
    
});

routes/web.php
<?php
//Route::get('/', function () {
//    return view('welcome');
//});

//Route::get('/','[controller/action]')
//文章列表页
Route::get('/posts','\App\Http\Controllers\PostController@index');
//创建文章
Route::get('/posts/create','\App\Http\Controllers\PostController@create');
Route::post('/posts','\App\Http\Controllers\PostController@store');
//文章详情
Route::get('/posts/{post}','\App\Http\Controllers\PostController@show');
//编辑文章
Route::get('/posts/{post}/edit','\App\Http\Controllers\PostController@edit');
Route::put('/posts/{post}','\App\Http\Controllers\PostController@update');
// 删除文章
Route::get('/posts/{post}/delete','\App\Http\Controllers\PostController@delete');
// 图片上传
Route::post('/posts/image/upload','\App\Http\Controllers\PostController@imageUpload');
//评论文章
Route::post('/posts/{post}/comment','\App\Http\Controllers\PostController@comment');
//赞
Route::get('/posts/{post}/zan','\App\Http\Controllers\PostController@zan');
//取消赞
Route::get('/posts/{post}/unzan','\App\Http\Controllers\PostController@unzan');


//注册页面
Route::get('/register','\App\Http\Controllers\RegisterController@index');
//注册行为
Route::post('/register','\App\Http\Controllers\RegisterController@register');
//登录页面
Route::get('/login','\App\Http\Controllers\LoginController@index');
//登录行为
Route::post('/login','\App\Http\Controllers\LoginController@login');
//退出行为
Route::get('/logout','\App\Http\Controllers\LoginController@logout');
//个人设置页面
Route::get('/user/me/setting','\App\Http\Controllers\UserController@setting');
//个人设置行为
Route::post('/user/me/setting','\App\Http\Controllers\UserController@settingStore');
//个人中心页面
Route::get('/user/{user}','\App\Http\Controllers\UserController@show');
//关注用户
Route::get('/user/{user}/fan','\App\Http\Controllers\UserController@fan');
//取消关注
Route::get('/user/{user}/unfan','\App\Http\Controllers\UserController@unfan');

//专题详情
Route::get('/topic/{topic}','\App\Http\Controllers\TopicController@show');
//投稿
Route::post('/topic/{topic}/submit','\App\Http\Controllers\TopicController@submit');

include_once("admin.php");

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;
class User extends Authenticatable
{
    protected $fillable = ['name','email','password']; 

    //用户文章列表
    public function posts()
    {
        return $this->hasMany(\App\Post::class,'user_id','id');
    }
    //关注我的fan模型
    public function fans()
    {
        return $this->hasMany(\App\Fan::class,'star_id','id');
    }
    //我关注的fan模型
    public function stars()
    {
        return $this->hasMany(\App\Fan::class,'fan_id','id');
    }
    //关注某人
    public function doFan($uid)
    {
        $fan = new \App\Fan();
        $fan->star_id = $uid;
        return $this->stars()->save($fans);
    }
    //取消关注某人
    public function doUnFan($uid)
    {
        $fan = new \App\Fan();
        $fan->star_id = $uid;
        return $this->stars()->delete($fans);
    }
    //当前用户是否被uid关注
    public function hasFan($uid)
    {
        return $this->fans()->where('fan_id',$uid)->count();
    }
    //当前用户是否关注了uid
    public function hasStar($uid)
    {
        return $this->stars()->where('star_id',$uid)->count();
    }

}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class UserController extends Controller
{
    public function setting()
    {
        return view('user/setting');
    }

     public function settingStore()
    {
         $this->validate(request(),[
            'name' => 'min:3',
        ]);

        $name = request('name');
        if ($name != $user->name) {
            if(\App\User::where('name', $name)->count() > 0) {
                return back()->withErrors(array('message' => '用户名称已经被注册'));
            }
            $user->name = request('name');
        }
        if ($request->file('avatar')) {
            $path = $request->file('avatar')->storePublicly(md5(\Auth::id() . time()));
            $user->avatar = "/storage/". $path;
        }
        $user->save();
        return back();

    }
     public function show()
    {
        //个人信息
        $user = User::withCount(['stars','fans','posts'])->find($user->id);
        //文章列表
        $posts = $user->posts()->orderBy('created_at','desc')->take(10)->get();
        //关注的用户
         $stars = $user->stars;
         $susers = User::whereIn('id',$fans->pluck('star_id'))->withCount(['stars','fans','posts'])->get();
        //粉丝用户
        $fans = $user->fans;
        $fuser = User::whereIn('id',$fans->pluck('fan_id'))->withCount(['stars','fans','posts'])->get();
        return view('user/show',compact('user','posts','susers','fusers'));
    }
    //关注用户
    public function fan()
    {
        $me = \Auth::user();
        $me->doFan($user->id);
        return [
            'error' => 0,
            'msg' => '',
        ];
    }
    //取消关注
     public function unfan()
    {
        $me = \Auth::user();
        $me->doUnFan($user->id);
        return [
            'error' => 0,
            'msg' => '',
        ];
    }
    
}

resources/views/user/setting.blade.php
@extends("layout.main")
@section("content")
    <div class="col-sm-8 blog-main">
        <form class="form-horizontal" action="/user/5/setting" method="POST" enctype="multipart/form-data">
            <input type="hidden" name="_token" value="RuzO8giZVe3C2PalHpxGydYXKvwqNxMwcxscznAb">
            <div class="form-group">
                <label class="col-sm-2 control-label">用户名</label>
                <div class="col-sm-10">
                    <input class="form-control" name="name" type="text" value="Kassandra Ankunding2">
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label">头像</label>
                <div class="col-sm-2">
                    <input class=" file-loading preview_input" type="file" value="用户名" style="width:72px" name="avatar">
                    <img  class="preview_img" src="image/user.jpeg" alt="" class="img-rounded" style="border-radius:500px;">
                </div>
            </div>
             @include('layout.error')
            <button type="submit" class="btn btn-default">修改</button>
        </form>
        <br>

    </div>


     @endsection

resources/views/user/show.blade.php
@extends("layout.main")
@section("content")


    <div class="col-sm-8">
        <blockquote>
            <p>
            <img src="{{$user->avatar}}" alt="" class="img-rounded" style="border-radius:500px; height: 40px"> 
            {{$user->name}}
            </p>
            <footer>关注：{{$user->stars_count}}｜粉丝：{{$user->fans_count}}｜文章：{{$user->posts_count}}</footer>
            @include('user.badges.like', ['target_user' => $user])
            </blockquote>
    </div>
    <div class="col-sm-8 blog-main">
        <div class="nav-tabs-custom">
            <ul class="nav nav-tabs">
                <li class="active"><a href="#tab_1" data-toggle="tab" aria-expanded="true">文章</a></li>
                <li class=""><a href="#tab_2" data-toggle="tab" aria-expanded="false">关注</a></li>
                <li class=""><a href="#tab_3" data-toggle="tab" aria-expanded="false">粉丝</a></li>
            </ul>
            <div class="tab-content">
                <div class="tab-pane active" id="tab_1">
                    @foreach($posts as $post)
                        <div class="blog-post" style="margin-top: 30px">
                            <p class=""><a href="/user/{{$post->user->id}}">{{$post->user->name}}</a> {{$post->created_at->diffForHumans()}}</p>
                            <p class=""><a href="/posts/{{$post->id}}" >{{$post->title}}</a></p>

                            <p>{!!str_limit($post->content,100,'...')!!}</p>
                        </div>
                    @endforeach                   
                  </div>
                <!-- /.tab-pane -->
                <div class="tab-pane" id="tab_2">
                 @foreach($susers as $user)
                    <div class="blog-post" style="margin-top: 30px">
                            <p class="">{{$user->name}}</p>
                            <p class="">关注：{{$user->stars_count}} | 粉丝：{{$user->fans_count}}｜ 文章：{{$user->posts_count}}</p>

                     <div>
                     @include('user.badges.like', ['target_user' => $user])
                  @endforeach       
                  </div>
                <!-- /.tab-pane -->
                <div class="tab-pane" id="tab_3">
                 @foreach($fans as $fan)
                        <?php $fuser = $fan->fuser()->first(); ?>
                        <div class="blog-post" style="margin-top: 30px">
                            <p class="">{{$fuser->name}}</p>
                            <p class="">关注：{{$fuser->stars()->count()}} | 粉丝：{{$fuser->fans()->count()}}｜ 文章：{{$fuser->posts()->count()}}</p>

                        @include('user.badges.like', ['target_user' => $user])
                        </div>
                    @endforeach
                   </div>
                <!-- /.tab-pane -->
            </div>
            <!-- /.tab-content -->
        </div>


    </div><!-- /.blog-main -->
@endsection


       